--- !ditz.rubyforge.org,2008-03-06/project 
name: lisp-matrix.git
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: lisp-matrix.git
- !ditz.rubyforge.org,2008-03-06/component 
  name: matrix
- !ditz.rubyforge.org,2008-03-06/component 
  name: vector
- !ditz.rubyforge.org,2008-03-06/component 
  name: blapack
- !ditz.rubyforge.org,2008-03-06/component 
  name: manip
- !ditz.rubyforge.org,2008-03-06/component 
  name: statnumeric
releases: []

